new tools
git-svn-id: file:///source/coreland/io_poll/trunk@1667 6e7d7e42-f3d6-da11-80d8-00d0b73f4485

diff --git a/mk-cctype b/mk-cctype
--- a/mk-cctype
+++ b/mk-cctype
@@ -1,4 +1,9 @@
-#!/bin/sh 
+#!/bin/sh
+
+cleanup()
+{
+  rm -f _mk_cctype.c _mk_cctype
+}
 
 SYS_CC=`head -n 1 conf-cc`
 if [ $? -ne 0 ]
@@ -6,95 +11,179 @@ then
   echo "fatal: could not read conf-cc" 1>&2
   exit 1
 fi
-SYS_TYPE=`head -n 1 conf-systype`
+
+( cat <<EOF
+#include <stdio.h>
+const char *var = "UNKNOWN";
+int main()
+{
+#if defined(__TURBOC__)
+  var = "BORLAND_TURBO_C";
+#endif
+#if defined(__BORLANDC__)
+  var = "BORLAND_CXX";
+#endif
+#if defined(__COMO__)
+  var = "COMEAU_CXX";
+#endif
+#if defined(__DECC) || defined(__VAXC) || defined(VAXC)
+  var = "COMPAQ_C";
+#endif
+#if defined(__DECCXX) || defined(__VAXC) || defined(VAXC)
+  var = "COMPAQ_CXX";
+#endif
+#if defined(_CRAYC)
+  var = "CRAY_C";
+#endif
+#if defined(__DCC__)
+  var = "DIAB";
+#endif
+#if defined(__DMC__) || defined(__SC__) || defined(__ZTC__)
+  var = "DIGITAL_MARS";
+#endif
+#if defined(__DJGPP__) || defined(__GO32__)
+  var = "DJGPP";
+#endif
+#if defined(__PATHCC__)
+  var = "EKOPATH";
+#endif
+#if defined(__GNUC__)
+  var = "GCC";
+#endif
+#if defined(__ghs__)
+  var = "GREENHILL";
+#endif
+#if defined(__HP_cc)
+  var = "HP_C";
+#endif
+#if defined(__HP_aCC)
+  var = "HP_ACC";
+#endif
+#if defined(__xlC__) || defined(__IBMC__) || defined(__IBMCPP__)
+  var = "IBM_XL";
+#endif
+#if defined(__IAR_SYSTEMS_ICC__)
+  var = "IAR";
+#endif
+#if defined(__INTEL_COMPILER) || defined(__ICC) || defined(__ECC) || defined(__ICL)
+  var = "INTEL";
+#endif
+#if defined(__KCC)
+  var = "KAI";
+#endif
+#if defined(__CA__) || defined(__KEIL__)
+  var = "KEIL_CARM";
+#endif
+#if defined(__C166__)
+  var = "KEIL_C166";
+#endif
+#if defined(__C51__) || defined(__CX51__)
+  var = "KEIL_C51";
+#endif
+#if defined(__LCC__)
+  var = "LCC";
+#endif
+#if defined(__llvm__)
+  var = "LLVM";
+#endif
+#if defined(__HIGHC__)
+  var = "METAWARE";
+#endif
+#if defined(__MWERKS__)
+  var = "CODEWARRIOR";
+#endif
+#if defined(__MINGW32__)
+  var = "MINGW32";
+#endif
+#if defined(__sgi) || defined(sgi)
+  var = "MIPSPRO";
+#endif
+#if defined(__MRC__) || defined(MPW_C) || defined(MPW_CPLUS)
+  var = "MPW";
+#endif
+#if defined(_MSC_VER)
+  var = "VISUAL_CXX";
+#endif
+#if defined(_MRI)
+  var = "MICROTEC";
+#endif
+#if defined(__CC_NORCROFT)
+  var = "NORCROFT";
+#endif
+#if defined(__PACIFIC__)
+  var = "PACIFIC";
+#endif
+#if defined(_PACC_VER)
+  var = "PALM";
+#endif
+#if defined(__POCC__)
+  var = "PELLES";
+#endif
+#if defined(__PGI)
+  var = "PORTLAND";
+#endif
+#if defined(__CC_ARM)
+  var = "REALVIEW";
+#endif
+#if defined(SASC) || defined(__SASC) || defined(__SASC__)
+  var = "SAS";
+#endif
+#if defined(_SCO_DS)
+  var = "SCO";
+#endif
+#if defined(SDCC)
+  var = "SMALLDEV";
+#endif
+#if defined(__SUNPRO_C)
+  var = "SUN_C";
+#endif
+#if defined(__SUNPRO_CC)
+  var = "SUN_CXX";
+#endif
+#if defined(__SYSC__)
+  var = "SYSTEMS";
+#endif
+#if defined(__TenDRA__)
+  var = "TENDRA";
+#endif
+#if defined(__TINYC__)
+  var = "TINYC";
+#endif
+#if defined(_UCC)
+  var = "ULTIMATE";
+#endif
+#if defined(__USLC__)
+  var = "USL_C";
+#endif
+#if defined(__WATCOMC__)
+  var = "WATCOM";
+#endif
+  printf("%s\n", var);
+  return 0;
+}
+EOF
+) > _mk_cctype.c
+
 if [ $? -ne 0 ]
 then
-  echo "fatal: could not read conf-systype" 1>&2
+  echo "fatal: could not create _mk_cctype.c" 1>&2
+  cleanup
+  exit 1
+fi
+${SYS_CC} -o _mk_cctype _mk_cctype.c
+if [ $? -ne 0 ]
+then
+  echo "fatal: could not create _mk_cctype" 1>&2
+  cleanup
+  exit 1
+fi
+./_mk_cctype
+if [ $? -ne 0 ]
+then
+  echo "fatal: could not create _mk_cctype" 1>&2
+  cleanup
   exit 1
 fi
 
-SYS_CCTYPE=""
-
-guess_compiler()
-{
-  cc_string="$1"
-
-  # try common targets
-  echo "${cc_string}" | grep 'gcc' 1>/dev/null 2>&1
-  if [ $? -eq 0 ]
-  then
-    echo 'gcc'
-    exit 0
-  fi
-  echo "${cc_string}" | grep 'compaq c' 1>/dev/null 2>&1
-  if [ $? -eq 0 ]
-  then
-    echo 'compaq-c'
-    exit 0
-  fi
-  echo "${cc_string}" | grep 'intel(r) c compiler' 1>/dev/null 2>&1
-  if [ $? -eq 0 ]
-  then
-    echo 'intel-c'
-    exit 0
-  fi
-
-  # make likely guesses based on system type
-  case "${SYS_TYPE}" in
-    hp-ux)
-      # the HP-UX C compiler utterly refuses to give any version
-      # information
-      # unless compiling. the C++ gives a version string, however.
-      echo "${cc_string}" | grep 'hp ac++/ansi c' 1>/dev/null 2>&1
-      if [ $? -eq 0 ]
-      then
-        echo 'hp-c'
-        exit 0
-      fi
-      touch .__hpuxcc__tmp.c
-      cc_string=`${SYS_CC} -V -c -o .__hpuxcc__tmp.o .__hpuxcc__tmp.c 2>&1`
-      cc_string=`echo ${cc_string} | tr [A-Z] [a-z] 2>&-`
-      echo "$cc_string" | grep 'hp c compiler' 1>/dev/null 2>&1
-      if [ $? -eq 0 ]
-      then
-        rm -f .__hpuxcc__tmp.c .__hpuxcc__tmp.o
-        echo 'hp-c'
-        exit 0
-      fi
-      rm -f .__hpuxcc__tmp.c .__hpuxcc__tmp.o
-      ;;
-    sunos)
-      # sun C considers using the -V flag an error...
-      cc_string=`${SYS_CC} -V 2>&1`
-      cc_string=`echo ${cc_string} | tr [A-Z] [a-z] 2>&-`
-      echo "${cc_string}" | grep 'sun c' 1>/dev/null 2>&1
-      if [ $? -eq 0 ]
-      then
-        echo 'sun-c'
-        exit 0
-      fi
-      ;;
-    *)
-      ;;
-  esac
-}
-
-# try -v flag first
-CC_OUTPUT=`${SYS_CC} -v 2>&1`
-if [ x"${CC_OUTPUT}" != "x" ]
-then
-  CC_OUTPUT=`echo ${CC_OUTPUT} | tr [A-Z] [a-z] 2>&-`
-  guess_compiler "${CC_OUTPUT}"
-fi
-
-# try -V flag
-CC_OUTPUT=`${SYS_CC} -V 2>&1`
-if [ x"${CC_OUTPUT}" != "x" ]
-then
-  CC_OUTPUT=`echo ${CC_OUTPUT} | tr [A-Z] [a-z] 2>&-`
-  guess_compiler "${CC_OUTPUT}"
-fi
-
-# give up
-echo "unknown"
-
+cleanup
+exit 0
